version: "3.8"

services:
  db:
    image: mongo:latest
    container_name: himawari-db
    volumes:
      - hima-mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
    ports:
      - 27017:27017
    restart: always
  db-mon:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASS}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=db
  nginx:
    image: nginx:latest
    container_name: himawari-nginx
    restart: always
    volumes:
      - ./nginx-templates:/etc/nginx/templates
      - ${CERT}:/etc/ssl/certs/server.crt
      - ${KEY}:/etc/ssl/certs/server.key
    ports:
      - 443:443
      - 80:80
    environment:
      - HIMAWARI_API=host.docker.internal:${SERVER_PORT}
      - HIMAWARI_FRONTEND=host.docker.internal:${FRONTEND_PORT}
      - DOMAIN=${DOMAIN}
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  hima-mongo:
    driver: local